; ============================================================
;  HarvestEye — PlatformIO Configuration
;  ESP32 IoT — Global Solution 2026/1
; ============================================================

[env:harvsteye]
platform    = espressif32
board       = esp32dev
framework   = arduino

monitor_speed = 115200

lib_deps =
    adafruit/DHT sensor library                 ; DHT22
    adafruit/Adafruit Unified Sensor            ; dependência do DHT
    marcoschwartz/LiquidCrystal_I2C             ; LCD 16x2 I2C
    bblanchon/ArduinoJson                       ; JSON

; WiFi, WebServer e HTTPClient já vêm embutidos no framework ESP32